ui_template:
  header:
    app_name: "Your Personal Career Assistant"
    subject_buttons:
      - label: "AI Basics"
        is_active: true
      - label: "GenAI"
        is_active: false
      - label: "Data Science"
        is_active: false
      - label: "LLMs"
        is_active: false

  sections:
    - title: "Well-being Check"
      components:
        - type: "emotional_coefficients"
          heading: "Current Emotional Coefficients"
          data:
            - label: "Anxiety"
              level: "High"
              color: "red"
            - label: "Uncertainty"
              level: "Medium"
              color: "yellow"
            - label: "Motivation"
              level: "High"
              color: "green"
        - type: "text_block"
          heading: "Clear Pathways to Reduce Anxiety"
          content: "Focus on a single, manageable step at a time. This roadmap is designed to break down your transition into clear, actionable goals. Start by exploring the 'AI Basics' course below to build a solid foundation. Celebrating small victories will help reduce anxiety and build confidence."

    - title: "Learning Roadmap Progress"
      components:
        - type: "progress_bar"
          heading: "Completion Rate"
          value: 45
          total: 100
          label: "45% of your AI & GenAI roadmap completed."

    - title: "Newly Acquired Skills"
      components:
        - type: "skill_badges"
          heading: "My Skill Badges"
          data:
            - "Python for AI"
            - "Neural Networks"
            - "Prompt Engineering"

    - title: "Personalized Learning Roadmap"
      components:
        - type: "learning_list"
          heading: "Online Courses"
          data:
            - title: "Udemy: The AI & GenAI Masterclass"
              description: "A project-based course for hands-on learning."
              source: "Udemy"
            - title: "Coursera: Deep Learning Specialization"
              description: "Taught by Andrew Ng, covers foundational concepts."
              source: "Coursera"
            - title: "Coursera: Generative AI with Large Language Models"
              description: "In-depth look at LLMs and their applications."
              source: "Coursera"
        - type: "learning_list"
          heading: "YouTube Videos"
          data:
            - title: "AI Explained: The Future of Generative AI"
              description: "High-level overview of current trends."
              source: "YouTube"
            - title: "3Blue1Brown: Neural Networks Explained"
              description: "Intuitive explanations with stunning visuals."
              source: "YouTube"
            - title: "Lex Fridman: AI Conversations with Experts"
              description: "Long-form interviews with leading researchers."
              source: "YouTube"
        - type: "learning_list"
          heading: "Books & Papers"
          data:
            - title: "Textbook: 'Deep Learning' by Goodfellow et al."
              description: "The authoritative resource for deep learning."
              source: "Textbook"
            - title: "Reference Book: 'AI Superpowers' by Kai-Fu Lee"
              description: "Geopolitical and economic context of AI."
              source: "Reference Book"
            - title: "Research Paper: 'Attention Is All You Need'"
              description: "The foundational paper on the Transformer architecture."
              source: "Research Paper"
            - title: "Gartner Report: Hype Cycle for AI, 2024"
              description: "Analyzes emerging technologies and their maturity."
              source: "Market Study"
        - type: "learning_list"
          heading: "Market Studies"
          data:
            - title: "BCG Report: The Generative AI Opportunity"
              description: "Strategic guide for businesses adopting GenAI."
              source: "Market Study"

  actions:
    - type: "button"
      label: "Add More Sources"
      action: "add_source"
